Include new required keyword argument for Pool in asyncpg 0.10
https://github.com/MagicStack/asyncpg/releases/tag/v0.10.0 added `max_inactive_connection_lifetime` as a new required keyword argument for `asyncpg.pool.Pool`. Without this change, an error occurs:

```
...
  File "c:\users\carso\venv\lib\site-packages\asyncpgsa\pgsingleton.py", line 34, in init
    self.__pool = await create_pool(*args, dialect=dialect, **kwargs)
  File "c:\users\carso\venv\lib\site-packages\asyncpgsa\pool.py", line 87, in create_pool
    **connect_kwargs)
  File "c:\users\carso\venv\lib\site-packages\asyncpgsa\pool.py", line 9, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() missing 1 required keyword-only argument: 'max_inactive_connection_lifetime'
```